language: ruby
sudo: false
cache: bundler
services: postgresql
bundler_args: --jobs=3 --retry=3 --without development
rvm:
  - 2.4.1

before_script:
  - psql -c 'CREATE DATABASE evemonk_test;' -U postgres
  - bundle exec rake db:create db:migrate
  - bin/bundle-audit update

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - bin/bundle-audit 
