swagger: '2.0'
info:
  title: 'EveMonk API'
  description: 'EveMonk REST API documentation'
  version: '0.1.0'
host: localhost:3000
schemes:
  - http
basePath: /api
produces:
  - application/json
paths:
  /signups:
    post:
      summary: Signup
      description: |
        Signup endpoint.
      parameters:
        - name: user[email]
          in: formData
          description: User email
          required: true
          type: string
        - name: user[password]
          in: formData
          description: User password
          required: true
          type: string
          format: password
        - name: user[password_confirmation]
          in: formData
          description: User password confirmation
          required: true
          type: string
          format: password
      tags:
        - signups
      responses:
        200:
          description: Signup
          schema:
            $ref: '#/definitions/OutputUser'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sessions:
    post:
      summary: Get user auth token
      description: |
        Signin user and return user with token.
      parameters:
        - name: session[email]
          in: formData
          description: User email
          required: true
          type: string
        - name: session[password]
          in: formData
          description: User password
          type: string
          format: password
      tags:
        - sessions
      responses:
        200:
          description: Response with User model with token
          schema:
            $ref: '#/definitions/OutputUser'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  OutputUser:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: User ID. e.g. "42"
      email:
        type: string
        description: User email. e.g. "me@example.com"
      token:
        type: string
        description: User auth token. e.g. "AAkoMiLatQHMngyuUU1vnh5b"
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
