development:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'foo'
  messages_type: 'string'

#test:
#  fluent_host:   '127.0.0.1'
#  fluent_port:   24224
#  tag:           'foo'
#  messages_type: 'string'
#
#production:
#  fluent_host:   '127.0.0.1'
#  fluent_port:   24224
#  tag:           'foo'
#  messages_type: 'string'
