production:
  pghero_capture_query_stats:
    class: Pghero::CaptureQueryStatsJob
    schedule: every 5m
  pghero_capture_space_stats:
    class: Pghero::CaptureSpaceStatsJob
    schedule: every day at 2 pm
  rails_pulse_summary:
    class: RailsPulse::SummaryJob
    schedule: every 5m
  rails_pulse_cleanup:
    class: RailsPulse::CleanupJob
    schedule: every day at 2 pm
  eve_server_status:
    class: Eve::ServerStatusJob
    schedule: every 1m
