:queues:
  - mailers
  - default

:concurrency: 5

:schedule:
#  pg_hero_query_stats:
#    every: 5m
#    class: Pghero::CaptureQueryStatsWorker
#    description: 'Collect postgresql query stats'
#  pg_hero_space_stats:
#    every: 1d
#    class: Pghero::CaptureSpaceStatsWorker
#    description: 'Collection postgresql space stats'
  eve_races:
    every: 1d
    class: Eve::RacesImporterWorker
    description: 'Import Races'
  eve_bloodlines:
    every: 1d
    class: Eve::BloodlinesImporterWorker
    description: 'Import Bloodlines'
  eve_ancestries:
    every: 1d
    class: Eve::AncestriesImporterWorker
    description: 'Import Ancestries'
  eve_factions:
    every: 1d
    class: Eve::FactionsImporterWorker
    description: 'Import Factions'
  eve_alliances:
    every: 1d
    class: Eve::AlliancesImporterWorker
    description: 'Import Alliances index'
  eve_alliances_local:
    every: 1d
    class: Eve::LocalAlliancesImporterWorker
    description: 'Import Alliances info'
#  eve_alliances_corporations:
#    every: 1d
#    class: Eve::AlliancesCorporationsImporterWorker
#    description: 'Update EveOnline Alliances Corporations'
#  eve_corporations:
#    every: 1d
#    class: Eve::CorporationsImporterWorker
#    description: 'Update EveOnline Corporations'
  eve_characters:
    every: 1d
    class: Eve::CharactersImporterWorker
    description: 'Import Characters info'
##  eve_types:
##    every: 1h
##    class: Eve::TypesImporterWorker
##    description: 'Update EveOnline Types'
#  eve_graphics:
#    every: 1d
#    class: Eve::GraphicsImporterWorker
#    description: 'Import Graphics index'
#  # eve_systems:
#  #   every: 1d
#  #   class: Eve::SystemsImporterWorker
