:queues:
  - mailers
  - default

:logfile: ./log/sidekiq.log
:concurrency: 5

:schedule:
  pg_hero_query_stats:
    every: 5m
    class: Pghero::CaptureQueryStatsWorker
    description: 'Collect postgresql query stats'
  pg_hero_space_stats:
    every: 1d
    class: Pghero::CaptureSpaceStatsWorker
    description: 'Collection postgresql space stats'
  eve_races:
    every: 1h
    class: Eve::RacesImporterWorker
    description: 'Update EveOnline Races'
  eve_bloodlines:
    every: 1h
    class: Eve::BloodlinesImporterWorker
    description: 'Update EveOnline Bloodlines'
  eve_ancestries:
    every: 1h
    class: Eve::AncestriesImporterWorker
    description: 'Update EveOnline Ancestries'
  eve_factions:
    every: 1h
    class: Eve::FactionsImporterWorker
    description: 'Update EveOnline Factions'
  eve_alliances:
    every: 1h
    class: Eve::AlliancesImporterWorker
    description: 'Update EveOnline Alliances'
  eve_graphics:
    every: 1h
    class: Eve::GraphicsImporterWorker
    description: 'Update EveOnline Graphics'
  # eve_systems:
  #   every: 1d
  #   class: Eve::SystemsImporterWorker
  eve_alliances_corporations:
    every: 1h
    class: Eve::AlliancesCorporationsImporterWorker
    description: 'Update EveOnline Alliances Corporations'
  eve_corporations:
    every: 1h
    class: Eve::CorporationsImporterWorker
    description: 'Update EveOnline Corporations'
  eve_characters:
    every: 1h
    class: Eve::CharactersImporterWorker
    description: 'Update EveOnline Characters'
#  eve_types:
#    every: 1h
#    class: Eve::TypesImporterWorker
#    description: 'Update EveOnline Types'
