:queues:
  - mailers
  - default

:schedule:
  eve_races:
    every: 1d
    class: Eve::RacesImporterWorker
    description: 'Update EveOnline Races'
  eve_alliances:
    every: 1d
    class: Eve::AlliancesImporterWorker
    description: 'Update EveOnline Alliances'
  eve_alliances_remove_old:
    every: 1d
    class: Eve::RemoveOldAlliancesImporterWorker
    description: 'Remove Old EveOnline Alliances'
  # eve_bloodlines:
  #   every: 1d
  #   class: EveBloodlinesWorker
  # eve_factions:
  #   every: 1d
  #   class: EveFactionsWorker
  # eve_ancestries:
  #   every: 1d
  #   class: EveAncestriesWorker
